# Generated by Django 3.0.5 on 2020-04-21 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='boolean',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
