# Generated by Django 3.0.5 on 2020-04-21 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20200421_1942'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='boolean',
        ),
        migrations.RemoveField(
            model_name='post',
            name='email',
        ),
        migrations.RemoveField(
            model_name='post',
            name='url',
        ),
    ]
